#' Filter remote CSV using pygeoapi filter-by-attribute process
#'
#' @description
#' Sends a POST request to the pygeoapi `filter-by-attribute` process,
#' providing a remote CSV URL and a set of attribute filters, and
#' returns the URL (`href`) to the filtered output CSV generated by the API.
#'
#' @family ocgapi
#' @param csv_url Character. URL of the CSV file to filter.
#' @param keep Named list. Each element name is a column in the CSV and each
#'   element value is a vector of values to retain. Example:
#'   `list(site_id = c("FP1", "FP10"))`.
#' @param comment Optional comment that will be stored in the API response.
#'
#' @return A character string with the `href` pointing to the filtered CSV.
#' @export
#'
#' @examples
#' \dontrun{
#' api_filter_by_attribute(
#'   csv_url = "https://aqua.igb-berlin.de/referencedata/aqua90m/spdata_species.csv",
#'   keep = list(site_id = c("FP1", "FP2"))
#' )
#' }
api_filter_by_attribute <- function(csv_url, keep, comment = NULL) {
  body <- list(
    inputs = list(
      csv_url = csv_url,
      keep = keep,
      comment = comment
    ),
    outputs = list(
      transmissionMode = "reference"
    )
  )

  resp <- httr::POST(
    url = "https://aqua.igb-berlin.de/pygeoapi-dev/processes/filter-by-attribute/execution",
    httr::add_headers(`Content-Type` = "application/json"),
    body = jsonlite::toJSON(body, auto_unbox = TRUE)
  )

  httr::stop_for_status(resp)

  out <- jsonlite::fromJSON(httr::content(resp, as = "text", encoding = "UTF-8"))

  if (is.null(out$href)) {
    stop("API did not return 'href'. Full response:\n",
         jsonlite::toJSON(out, pretty = TRUE))
  }

  return(out$href)
}
